# Generated by Django 4.2.3 on 2023-07-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_employee_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eage',
            field=models.IntegerField(default=20),
        ),
    ]
