# Generated by Django 4.2.3 on 2023-07-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0003_employee_eage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='edesn',
            new_name='edesgn',
        ),
    ]
